AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Enabled: no

Metrics/AbcSize:
  Enabled: no

Metrics/BlockLength:
  Enabled: no

Metrics/MethodLength:
  Enabled: no

Style/Documentation:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: yes
  EnforcedStyle: always
  Include:
    - 'lib/**/*'

Naming/FileName:
  Enabled: no
