language: ruby
rvm:
  - 2.4.1
  - jruby-9.1.5.0
addons:
  code_climate:
    repo_token: 1f3842b985fdeff6a36168165d491ca5f444667e9381a85c899a61706a9dd285
services:
  - rabbitmq
before_script:
  - gem install bundler
  - bundle install
script: bundle exec rspec
